2023-04-04 15:21:57,762 INFO    MainThread:18692 [wandb_setup.py:_flush():68] Configure stats pid to 18692
2023-04-04 15:21:57,762 INFO    MainThread:18692 [wandb_setup.py:_flush():68] Loading settings from C:\Users\MSI\.config\wandb\settings
2023-04-04 15:21:57,762 INFO    MainThread:18692 [wandb_setup.py:_flush():68] Loading settings from D:\Projects\PFedTrans\system\wandb\settings
2023-04-04 15:21:57,762 INFO    MainThread:18692 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-04-04 15:21:57,762 INFO    MainThread:18692 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'main.py'}
2023-04-04 15:21:57,762 INFO    MainThread:18692 [wandb_init.py:_log_setup():492] Logging user logs to D:\Projects\PFedTrans\system\wandb\run-20230404_152157-511zau8e\logs\debug.log
2023-04-04 15:21:57,762 INFO    MainThread:18692 [wandb_init.py:_log_setup():493] Logging internal logs to D:\Projects\PFedTrans\system\wandb\run-20230404_152157-511zau8e\logs\debug-internal.log
2023-04-04 15:21:57,763 INFO    MainThread:18692 [wandb_init.py:init():532] calling init triggers
2023-04-04 15:21:57,763 INFO    MainThread:18692 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.005, 'number_of_client': 100, 'epochs': 200}
2023-04-04 15:21:57,763 INFO    MainThread:18692 [wandb_init.py:init():588] starting backend
2023-04-04 15:21:57,763 INFO    MainThread:18692 [wandb_init.py:init():592] setting up manager
2023-04-04 15:21:57,764 INFO    MainThread:18692 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-04-04 15:21:57,768 INFO    MainThread:18692 [wandb_init.py:init():599] backend started and connected
2023-04-04 15:21:57,769 INFO    MainThread:18692 [wandb_init.py:init():687] updated telemetry
2023-04-04 15:21:57,769 INFO    MainThread:18692 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-04-04 15:22:58,395 ERROR   MainThread:18692 [wandb_init.py:init():741] backend process timed out, exiting...
encountered error: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-04-04 15:22:58,400 ERROR   MainThread:18692 [wandb_init.py:init():1160] error
Traceback (most recent call last):
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\wandb\sdk\wandb_init.py", line 1133, in init
    run = wi.init()
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\wandb\sdk\wandb_init.py", line 759, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
