2023-04-05 22:53:28,697 INFO    StreamThr :48596 [internal.py:wandb_internal():87] W&B internal server running at pid: 48596, started at: 2023-04-05 22:53:28.696627
2023-04-05 22:53:28,698 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status
2023-04-05 22:53:28,699 INFO    WriterThread:48596 [datastore.py:open_for_write():85] open: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\run-7rgqvahr.wandb
2023-04-05 22:53:28,703 DEBUG   SenderThread:48596 [sender.py:send():336] send: header
2023-04-05 22:53:28,703 DEBUG   SenderThread:48596 [sender.py:send():336] send: run
2023-04-05 22:53:29,921 INFO    SenderThread:48596 [dir_watcher.py:__init__():216] watching files in: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files
2023-04-05 22:53:29,923 INFO    SenderThread:48596 [sender.py:_start_run_threads():1067] run started: 7rgqvahr with start time 1680706408.697627
2023-04-05 22:53:29,923 DEBUG   SenderThread:48596 [sender.py:send_request():363] send_request: summary_record
2023-04-05 22:53:29,923 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: check_version
2023-04-05 22:53:29,923 INFO    SenderThread:48596 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-04-05 22:53:29,924 DEBUG   SenderThread:48596 [sender.py:send_request():363] send_request: check_version
2023-04-05 22:53:29,940 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: run_start
2023-04-05 22:53:29,974 DEBUG   HandlerThread:48596 [system_info.py:__init__():31] System info init
2023-04-05 22:53:29,975 DEBUG   HandlerThread:48596 [system_info.py:__init__():46] System info init done
2023-04-05 22:53:29,975 INFO    HandlerThread:48596 [system_monitor.py:start():151] Starting system monitor
2023-04-05 22:53:29,975 INFO    SystemMonitor:48596 [system_monitor.py:_start():116] Starting system asset monitoring threads
2023-04-05 22:53:29,975 INFO    HandlerThread:48596 [system_monitor.py:probe():172] Collecting system info
2023-04-05 22:53:29,984 INFO    SystemMonitor:48596 [interfaces.py:start():168] Started cpu
2023-04-05 22:53:29,985 INFO    SystemMonitor:48596 [interfaces.py:start():168] Started disk
2023-04-05 22:53:29,985 INFO    SystemMonitor:48596 [interfaces.py:start():168] Started gpu
2023-04-05 22:53:29,998 INFO    SystemMonitor:48596 [interfaces.py:start():168] Started memory
2023-04-05 22:53:30,013 INFO    SystemMonitor:48596 [interfaces.py:start():168] Started network
2023-04-05 22:53:30,032 DEBUG   HandlerThread:48596 [system_info.py:probe():195] Probing system
2023-04-05 22:53:30,033 DEBUG   HandlerThread:48596 [system_info.py:probe():241] Probing system done
2023-04-05 22:53:30,033 DEBUG   HandlerThread:48596 [system_monitor.py:probe():181] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.8.11', 'heartbeatAt': '2023-04-05T14:53:30.033443', 'startedAt': '2023-04-05T14:53:28.687619', 'docker': None, 'cuda': None, 'args': ('-lbs', '16', '-nc', '20', '-jr', '1', '-nb', '10', '-data', 'Cifar10', '-m', 'dnn', '-algo', 'FedProto', '-gr', '1000', '-did', '0', '-go', 'dnn', '-wandb', 'True'), 'state': 'running', 'program': 'main.py', 'codePath': 'main.py', 'host': 'DESKTOP-HSUG78F', 'username': 'MSI', 'executable': 'C:\\Users\\MSI\\miniconda3\\envs\\d2l\\python.exe', 'cpu_count': 12, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3701.0, 'min': 0.0, 'max': 3701.0}, 'cpu_freq_per_core': [{'current': 3701.0, 'min': 0.0, 'max': 3701.0}], 'disk': {'total': 347.65429306030273, 'used': 152.2295799255371}, 'gpu': 'NVIDIA GeForce RTX 3080 Ti', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3080 Ti', 'memory_total': 12884901888}], 'memory': {'total': 31.927108764648438}}
2023-04-05 22:53:30,033 INFO    HandlerThread:48596 [system_monitor.py:probe():182] Finished collecting system info
2023-04-05 22:53:30,033 INFO    HandlerThread:48596 [system_monitor.py:probe():185] Publishing system info
2023-04-05 22:53:30,033 DEBUG   HandlerThread:48596 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-04-05 22:53:30,034 DEBUG   HandlerThread:48596 [system_info.py:_save_pip():67] Saving pip packages done
2023-04-05 22:53:30,034 DEBUG   HandlerThread:48596 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-04-05 22:53:30,039 ERROR   HandlerThread:48596 [system_info.py:_save_conda():85] Error saving conda packages: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 81, in _save_conda
    subprocess.call(
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
2023-04-05 22:53:30,040 DEBUG   HandlerThread:48596 [system_info.py:_save_conda():86] Saving conda packages done
2023-04-05 22:53:30,040 INFO    HandlerThread:48596 [system_monitor.py:probe():187] Finished publishing system info
2023-04-05 22:53:30,046 DEBUG   SenderThread:48596 [sender.py:send():336] send: files
2023-04-05 22:53:30,046 INFO    SenderThread:48596 [sender.py:_save_file():1321] saving file wandb-metadata.json with policy now
2023-04-05 22:53:30,056 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: stop_status
2023-04-05 22:53:30,056 DEBUG   SenderThread:48596 [sender.py:send_request():363] send_request: stop_status
2023-04-05 22:53:30,647 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2004] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-04-05 22:53:30,647 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2006] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2023-04-05 22:53:30,647 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2008] upload_file response body: 
2023-04-05 22:53:30,660 DEBUG   SenderThread:48596 [sender.py:send():336] send: telemetry
2023-04-05 22:53:30,938 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\wandb-summary.json
2023-04-05 22:53:30,938 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\wandb-metadata.json
2023-04-05 22:53:30,939 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\conda-environment.yaml
2023-04-05 22:53:30,939 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\requirements.txt
2023-04-05 22:53:30,939 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:53:31,723 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2004] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-04-05 22:53:31,723 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2006] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2023-04-05 22:53:31,723 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2008] upload_file response body: 
2023-04-05 22:53:32,953 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:53:33,825 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:53:34,117 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2004] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-04-05 22:53:34,117 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2006] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2023-04-05 22:53:34,117 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2008] upload_file response body: 
2023-04-05 22:53:34,117 INFO    wandb-upload_0:48596 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1999, in upload_file
    response = self._upload_file_session.put(
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2028, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1999, in upload_file
    response = self._upload_file_session.put(
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-04-05 22:53:34,971 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:53:36,987 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:53:38,433 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2004] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-04-05 22:53:38,433 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2006] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2023-04-05 22:53:38,433 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2008] upload_file response body: 
2023-04-05 22:53:39,016 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:53:39,134 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:53:41,040 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:53:43,062 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:53:44,997 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:53:45,059 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:53:45,059 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:53:45,075 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:53:47,095 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:53:47,119 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2004] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-04-05 22:53:47,119 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2006] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2023-04-05 22:53:47,119 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2008] upload_file response body: 
2023-04-05 22:53:49,109 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:53:50,032 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:53:50,099 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:53:51,131 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:53:53,158 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:53:55,140 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:53:55,188 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:53:55,971 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:53:57,204 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:53:59,231 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:00,194 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:54:01,195 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:54:01,253 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:02,265 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\config.yaml
2023-04-05 22:54:03,279 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:05,250 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:54:05,297 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:06,263 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2004] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-04-05 22:54:06,263 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2006] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2023-04-05 22:54:06,263 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2008] upload_file response body: 
2023-04-05 22:54:07,324 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:07,630 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:54:09,340 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:10,313 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:54:11,362 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:12,703 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:54:13,381 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:15,343 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:54:15,390 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:17,414 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:17,935 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:54:19,431 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:20,395 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:54:21,437 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:23,442 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:23,565 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:54:25,409 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:54:25,457 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:27,488 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:28,820 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:54:29,500 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:30,021 DEBUG   SystemMonitor:48596 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2023-04-05 22:54:30,022 DEBUG   SenderThread:48596 [sender.py:send():336] send: stats
2023-04-05 22:54:30,444 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:54:31,513 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:33,531 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:34,552 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:54:35,488 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:54:37,562 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:39,741 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:54:40,383 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2004] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-04-05 22:54:40,383 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2006] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2023-04-05 22:54:40,383 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2008] upload_file response body: 
2023-04-05 22:54:40,526 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:54:41,590 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:45,229 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:54:45,572 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:54:45,634 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:49,694 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:50,409 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:54:50,624 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:54:53,737 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:55,560 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:54:55,682 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:54:55,761 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:57,799 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:54:59,834 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:00,026 DEBUG   SenderThread:48596 [sender.py:send():336] send: stats
2023-04-05 22:55:00,717 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:55:01,144 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:55:01,878 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:03,896 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:05,782 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:55:05,930 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:06,985 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:55:07,958 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:10,000 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:10,837 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:55:12,034 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:12,967 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:55:15,884 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:55:16,124 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:17,977 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:55:18,158 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:20,187 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:20,922 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:55:22,218 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:23,855 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:55:24,268 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:25,960 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:55:26,298 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:28,910 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:55:30,037 DEBUG   SenderThread:48596 [sender.py:send():336] send: stats
2023-04-05 22:55:30,381 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:31,006 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:55:34,467 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:34,516 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:55:36,041 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:55:36,499 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:37,515 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:39,542 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:39,648 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:55:41,088 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:55:41,602 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:43,634 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:45,539 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:55:45,665 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:46,134 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:55:47,695 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:49,727 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:50,842 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:55:51,178 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:55:51,764 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:53,596 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2004] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/gerid/fedtrans_exp/7rgqvahr/wandb-metadata.json?Expires=1680792810&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JsHSDW2Vs%2FB%2Bkx7z2NqTtcZh7mABHXXgzgAxXM4PfAwcAzcPddEEtPhh5idjlhZewgbnp4Dyl5aU1XMXiKrnaRkU1DkspougN1SfK0sQbF10EH6cIGdG1zAod7OqhhUIFQP9kgXbJ1YF2iLr0XpC7ozHTEYMUntNuYeV4xtvPwiihiJIOMHbAUHg1NnV1alO3KFdVlVQSolv0u3HwdIZ5z7F%2BZOkVS%2BS%2BIixnkxwGQn4OXMdZacyvSgZZuR1ycYvKM2q4LT5vmxnNOAis7gd9JqXhwVvMvA%2Bm1qvSoAopLOJ2lN8ski6dY0UiKUXS2XCHY3Ka5jqsLh1VvsWXGh5dQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-04-05 22:55:53,596 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2006] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2023-04-05 22:55:53,596 ERROR   wandb-upload_0:48596 [internal_api.py:upload_file():2008] upload_file response body: 
2023-04-05 22:55:53,803 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:55,845 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:56,214 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:55:56,640 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:55:57,876 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:55:59,916 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:00,039 DEBUG   SenderThread:48596 [sender.py:send():336] send: stats
2023-04-05 22:56:01,247 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:56:01,944 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:01,974 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:56:04,002 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:06,040 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:06,291 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:56:07,204 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:56:08,076 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:10,115 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:11,336 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:56:12,139 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:12,308 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:56:14,172 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:16,214 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:16,382 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:56:18,243 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:18,302 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:56:20,273 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:21,437 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:56:22,300 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:24,204 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:56:24,327 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:26,367 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:26,503 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:56:28,425 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:29,561 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:56:30,052 DEBUG   SenderThread:48596 [sender.py:send():336] send: stats
2023-04-05 22:56:30,480 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:31,553 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:56:32,511 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:34,558 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:35,371 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:56:36,596 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:56:36,597 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:38,631 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:40,508 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:56:40,663 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:41,638 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: keepalive
2023-04-05 22:56:44,722 INFO    Thread-13 :48596 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Projects\PFedTrans\system\wandb\run-20230405_225328-7rgqvahr\files\output.log
2023-04-05 22:56:46,196 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:56:51,230 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:56:56,276 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:57:00,059 DEBUG   SenderThread:48596 [sender.py:send():336] send: stats
2023-04-05 22:57:02,095 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:57:07,138 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:57:12,193 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:57:17,244 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:57:22,287 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:57:27,335 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:57:30,073 DEBUG   SenderThread:48596 [sender.py:send():336] send: stats
2023-04-05 22:57:33,103 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:57:38,146 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 22:57:43,187 DEBUG   HandlerThread:48596 [handler.py:handle_request():144] handle_request: status_report
