2023-04-05 21:33:07,028 INFO    StreamThr :8332 [internal.py:wandb_internal():87] W&B internal server running at pid: 8332, started at: 2023-04-05 21:33:07.027927
2023-04-05 21:33:07,028 DEBUG   HandlerThread:8332 [handler.py:handle_request():144] handle_request: status
2023-04-05 21:33:07,030 INFO    WriterThread:8332 [datastore.py:open_for_write():85] open: D:\Projects\PFedTrans\system\wandb\offline-run-20230405_213307-va5t0xzn\run-va5t0xzn.wandb
2023-04-05 21:33:07,032 DEBUG   HandlerThread:8332 [handler.py:handle_request():144] handle_request: run_start
2023-04-05 21:33:07,065 DEBUG   HandlerThread:8332 [system_info.py:__init__():31] System info init
2023-04-05 21:33:07,065 DEBUG   HandlerThread:8332 [system_info.py:__init__():46] System info init done
2023-04-05 21:33:07,066 INFO    HandlerThread:8332 [system_monitor.py:start():151] Starting system monitor
2023-04-05 21:33:07,066 INFO    SystemMonitor:8332 [system_monitor.py:_start():116] Starting system asset monitoring threads
2023-04-05 21:33:07,066 INFO    HandlerThread:8332 [system_monitor.py:probe():172] Collecting system info
2023-04-05 21:33:07,074 INFO    SystemMonitor:8332 [interfaces.py:start():168] Started cpu
2023-04-05 21:33:07,075 INFO    SystemMonitor:8332 [interfaces.py:start():168] Started disk
2023-04-05 21:33:07,075 INFO    SystemMonitor:8332 [interfaces.py:start():168] Started gpu
2023-04-05 21:33:07,085 INFO    SystemMonitor:8332 [interfaces.py:start():168] Started memory
2023-04-05 21:33:07,111 INFO    SystemMonitor:8332 [interfaces.py:start():168] Started network
2023-04-05 21:33:07,118 DEBUG   HandlerThread:8332 [system_info.py:probe():195] Probing system
2023-04-05 21:33:07,118 DEBUG   HandlerThread:8332 [system_info.py:probe():241] Probing system done
2023-04-05 21:33:07,118 DEBUG   HandlerThread:8332 [system_monitor.py:probe():181] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.8.11', 'heartbeatAt': '2023-04-05T13:33:07.118368', 'startedAt': '2023-04-05T13:33:07.018252', 'docker': None, 'cuda': None, 'args': ('-lbs', '16', '-nc', '20', '-jr', '1', '-nb', '10', '-data', 'Cifar10', '-m', 'dnn', '-algo', 'Ditto', '-gr', '1000', '-did', '0', '-go', 'dnn', '-wandb', 'True'), 'state': 'running', 'program': 'main.py', 'codePath': 'main.py', 'host': 'DESKTOP-HSUG78F', 'username': 'MSI', 'executable': 'C:\\Users\\MSI\\miniconda3\\envs\\d2l\\python.exe', 'cpu_count': 12, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3701.0, 'min': 0.0, 'max': 3701.0}, 'cpu_freq_per_core': [{'current': 3701.0, 'min': 0.0, 'max': 3701.0}], 'disk': {'total': 347.65429306030273, 'used': 152.22493362426758}, 'gpu': 'NVIDIA GeForce RTX 3080 Ti', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3080 Ti', 'memory_total': 12884901888}], 'memory': {'total': 31.927108764648438}}
2023-04-05 21:33:07,118 INFO    HandlerThread:8332 [system_monitor.py:probe():182] Finished collecting system info
2023-04-05 21:33:07,118 INFO    HandlerThread:8332 [system_monitor.py:probe():185] Publishing system info
2023-04-05 21:33:07,118 DEBUG   HandlerThread:8332 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-04-05 21:33:07,119 DEBUG   HandlerThread:8332 [system_info.py:_save_pip():67] Saving pip packages done
2023-04-05 21:33:07,119 DEBUG   HandlerThread:8332 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-04-05 21:33:07,124 ERROR   HandlerThread:8332 [system_info.py:_save_conda():85] Error saving conda packages: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 81, in _save_conda
    subprocess.call(
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
2023-04-05 21:33:07,125 DEBUG   HandlerThread:8332 [system_info.py:_save_conda():86] Saving conda packages done
2023-04-05 21:33:07,126 INFO    HandlerThread:8332 [system_monitor.py:probe():187] Finished publishing system info
2023-04-05 21:33:10,208 DEBUG   HandlerThread:8332 [handler.py:handle_request():144] handle_request: partial_history
2023-04-05 21:33:12,083 DEBUG   HandlerThread:8332 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 21:33:12,084 DEBUG   SenderThread:8332 [sender.py:send_request():363] send_request: status_report
2023-04-05 21:33:13,220 DEBUG   HandlerThread:8332 [handler.py:handle_request():144] handle_request: partial_history
2023-04-05 21:33:16,140 WARNING StreamThr :8332 [internal.py:is_dead():415] Internal process exiting, parent pid 18020 disappeared
2023-04-05 21:33:16,141 ERROR   StreamThr :8332 [internal.py:wandb_internal():153] Internal process shutdown.
2023-04-05 21:33:16,324 INFO    WriterThread:8332 [datastore.py:close():299] close: D:\Projects\PFedTrans\system\wandb\offline-run-20230405_213307-va5t0xzn\run-va5t0xzn.wandb
2023-04-05 21:33:16,324 INFO    HandlerThread:8332 [handler.py:finish():841] shutting down handler
2023-04-05 21:33:17,143 ERROR   cpu       :8332 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=18020)
2023-04-05 21:33:17,148 ERROR   cpu       :8332 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=18020)
2023-04-05 21:33:17,152 INFO    SenderThread:8332 [sender.py:finish():1493] shutting down sender
