2023-04-05 21:31:53,719 INFO    StreamThr :31420 [internal.py:wandb_internal():87] W&B internal server running at pid: 31420, started at: 2023-04-05 21:31:53.718845
2023-04-05 21:31:53,719 DEBUG   HandlerThread:31420 [handler.py:handle_request():144] handle_request: status
2023-04-05 21:31:53,722 INFO    WriterThread:31420 [datastore.py:open_for_write():85] open: D:\Projects\PFedTrans\system\wandb\offline-run-20230405_213153-b88vk7k1\run-b88vk7k1.wandb
2023-04-05 21:31:53,724 DEBUG   HandlerThread:31420 [handler.py:handle_request():144] handle_request: run_start
2023-04-05 21:31:53,759 DEBUG   HandlerThread:31420 [system_info.py:__init__():31] System info init
2023-04-05 21:31:53,760 DEBUG   HandlerThread:31420 [system_info.py:__init__():46] System info init done
2023-04-05 21:31:53,760 INFO    HandlerThread:31420 [system_monitor.py:start():151] Starting system monitor
2023-04-05 21:31:53,760 INFO    SystemMonitor:31420 [system_monitor.py:_start():116] Starting system asset monitoring threads
2023-04-05 21:31:53,760 INFO    HandlerThread:31420 [system_monitor.py:probe():172] Collecting system info
2023-04-05 21:31:53,768 INFO    SystemMonitor:31420 [interfaces.py:start():168] Started cpu
2023-04-05 21:31:53,768 INFO    SystemMonitor:31420 [interfaces.py:start():168] Started disk
2023-04-05 21:31:53,769 INFO    SystemMonitor:31420 [interfaces.py:start():168] Started gpu
2023-04-05 21:31:53,778 INFO    SystemMonitor:31420 [interfaces.py:start():168] Started memory
2023-04-05 21:31:53,791 INFO    SystemMonitor:31420 [interfaces.py:start():168] Started network
2023-04-05 21:31:53,798 DEBUG   HandlerThread:31420 [system_info.py:probe():195] Probing system
2023-04-05 21:31:53,811 DEBUG   HandlerThread:31420 [system_info.py:probe():241] Probing system done
2023-04-05 21:31:53,811 DEBUG   HandlerThread:31420 [system_monitor.py:probe():181] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.8.11', 'heartbeatAt': '2023-04-05T13:31:53.811189', 'startedAt': '2023-04-05T13:31:53.708494', 'docker': None, 'cuda': None, 'args': ('-lbs', '16', '-nc', '20', '-jr', '1', '-nb', '10', '-data', 'Cifar10', '-m', 'dnn', '-algo', 'Ditto', '-gr', '1000', '-did', '0', '-go', 'dnn', '-wandb', 'True'), 'state': 'running', 'program': 'main.py', 'codePath': 'main.py', 'host': 'DESKTOP-HSUG78F', 'username': 'MSI', 'executable': 'C:\\Users\\MSI\\miniconda3\\envs\\d2l\\python.exe', 'cpu_count': 12, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3701.0, 'min': 0.0, 'max': 3701.0}, 'cpu_freq_per_core': [{'current': 3701.0, 'min': 0.0, 'max': 3701.0}], 'disk': {'total': 347.65429306030273, 'used': 152.22491455078125}, 'gpu': 'NVIDIA GeForce RTX 3080 Ti', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3080 Ti', 'memory_total': 12884901888}], 'memory': {'total': 31.927108764648438}}
2023-04-05 21:31:53,811 INFO    HandlerThread:31420 [system_monitor.py:probe():182] Finished collecting system info
2023-04-05 21:31:53,811 INFO    HandlerThread:31420 [system_monitor.py:probe():185] Publishing system info
2023-04-05 21:31:53,811 DEBUG   HandlerThread:31420 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-04-05 21:31:53,812 DEBUG   HandlerThread:31420 [system_info.py:_save_pip():67] Saving pip packages done
2023-04-05 21:31:53,812 DEBUG   HandlerThread:31420 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-04-05 21:31:53,816 ERROR   HandlerThread:31420 [system_info.py:_save_conda():85] Error saving conda packages: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 81, in _save_conda
    subprocess.call(
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\MSI\miniconda3\envs\d2l\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
2023-04-05 21:31:53,817 DEBUG   HandlerThread:31420 [system_info.py:_save_conda():86] Saving conda packages done
2023-04-05 21:31:53,818 INFO    HandlerThread:31420 [system_monitor.py:probe():187] Finished publishing system info
2023-04-05 21:31:56,948 DEBUG   HandlerThread:31420 [handler.py:handle_request():144] handle_request: partial_history
2023-04-05 21:31:58,783 DEBUG   HandlerThread:31420 [handler.py:handle_request():144] handle_request: status_report
2023-04-05 21:31:58,783 DEBUG   SenderThread:31420 [sender.py:send_request():363] send_request: status_report
2023-04-05 21:31:59,909 DEBUG   HandlerThread:31420 [handler.py:handle_request():144] handle_request: partial_history
2023-04-05 21:32:01,873 ERROR   cpu       :31420 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=48844)
2023-04-05 21:32:01,878 ERROR   cpu       :31420 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=48844)
2023-04-05 21:32:01,892 ERROR   memory    :31420 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=48844)
2023-04-05 21:32:01,895 ERROR   memory    :31420 [interfaces.py:monitor():129] Failed to sample metric: process no longer exists (pid=48844)
2023-04-05 21:32:02,795 WARNING StreamThr :31420 [internal.py:is_dead():415] Internal process exiting, parent pid 48844 disappeared
2023-04-05 21:32:02,795 ERROR   StreamThr :31420 [internal.py:wandb_internal():153] Internal process shutdown.
2023-04-05 21:32:02,819 INFO    SenderThread:31420 [sender.py:finish():1493] shutting down sender
2023-04-05 21:32:02,819 INFO    MainThread:31420 [internal.py:handle_exit():77] Internal process exited
